homeassistant:
  name: Casa
  # Localização, usada para determinar quando o sol nasce e se põe
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: !secret elevation
  unit_system: metric
  # Selecione timezone aqui: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Sao_Paulo
  customize: !include customize.yaml

  customize_glob:
  #Oculta sensores IGD (agregados pelo UPNP)
#    "sensor.igd_*":
#      hidden: true
    "automation.*":
      hidden: true

# Enables the frontend
frontend:

# Enables configuration UI
config:

# Log de falhas no diretorio .homeassistant
logger:
  default: warning
  logs:
    #Oculta logs de erro da camera (erro na biblioteca)
    requests.packages.urllib3: critical
    urllib3.connectionpool: critical

http:
  # Senha do home assistant
  api_password: !secret password01
#  ssl_certificate: !secret ssl_certificate
#  ssl_key: !secret ssl_key
#  use_x_forwarded_for: True
  ip_ban_enabled: True
  login_attempts_threshold: 5

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
#  base_url: http://blablabla.duckdns.net:8123

#upnp:

# Procura por atualizações do sistema
updater:

# Descobre novos dispositivos
discovery:

# Comandos por voz na interface web
#conversation:

# Salva dados em banco de dados SQLite
recorder:
  exclude:
    domains:
      - camera
    entities:
      - sun.sun
      - sensor.since_last_boot
      - sensor.since_last_boot_templated
      - sensor.ram_used
      - sensor.cpu_used
      
# Habilita histórico
history:
  exclude:
    domains:
      - automation
      - script
      - persistent_notification
      - group
      - input_number
      - camera
      - switch
      - weblink
    entities:
      - sensor.ram_use
      - sensor.cpu_use
      - sensor.disk_use_mntssd
      - sensor.alexandre

# Habilita logbook
logbook:
  exclude:
    domains:
    - automation

# Monitora o sol - que pode ser usado em automações
sun:

#Zonas de interesse
zone: !include zones.yaml

# Sensor do clima
sensor:
  - platform: yr
    monitored_conditions:
      - temperature
      - humidity
# Tempo de viagem para locais de interesse, via Google Maps
  - platform: google_travel_time
    name: Unitec Semicondutores
    api_key: !secret google_api_key
    origin: Casa
    destination: Unitec Semicondutores
    hidden: true
  - platform: google_travel_time
    name: Alexandre -> Casa
    api_key: !secret google_api_key
    origin: device_tracker.0023141914
    destination: Casa
    hidden: true
  - platform: google_travel_time
    name: Hospital Militar
    api_key: !secret google_api_key 
    origin: Casa
    destination: Hospital da Polícia Militar de Belo Horizonte
    options:
      mode: transit
    hidden: true
#Testa a velocidade da internet
  - platform: speedtest
    monitored_conditions:
      - ping
      - download
      - upload
#Monitora o estado do OPi
  - platform: systemmonitor
    resources:
      - type: disk_use_percent
        arg: /mnt/ssd
      - type: memory_use_percent
      - type: since_last_boot
      - type: processor_use
  - platform: command_line
    name: Temperatura da CPU
    command: cat /etc/armbianmonitor/datasources/soctemp
    unit_of_measurement: "°C"
    scan_interval: 300
  - platform: template
    sensors:
      alexandre:
        value_template: >-
          {%- if is_state("device_tracker.0023141914", "not_home") -%}
            {{ states.sensor.alexandre__casa.attributes.origin_addresses[0][0:states.sensor.alexandre__casa.attributes.origin_addresses[0]|length-13] }}
          {%- else -%}
            {{ states("device_tracker.0023141914") }}
          {%- endif -%}
  - platform: template
    sensors:
      bateria_alexandre:
        friendly_name: "Celular Alexandre"
        value_template: >-
          {%- if is_state("device_tracker.0023141914", "unknown") -%}
            0
          {%- else -%}
            {{ states.device_tracker['0023141914'].attributes.battery }}
          {%- endif -%}
        unit_of_measurement: '%'
   # Converte o uptime para facilitar leitura
  - platform: template
    sensors:
      since_last_boot_templated:
        value_template: >-
          {%- set slb = states.sensor.since_last_boot.state.split(' ') -%}
          {%- set count = slb | length -%}
          {%- set hms = slb[count - 1] -%}
          {%- set hms_trimmed = hms.split('.')[0] -%}
          {%- set hms_split = hms_trimmed.split(':') -%}
          {%- set hours = hms_split[0] | int -%}
          {%- set minutes = hms_split[1] | int -%}
          {%- set seconds = hms_split[2] | int -%}

          {%- if count == 3 -%}
            {{ slb[0] ~ ' ' ~ slb[1] ~ ' ' }}
          {%- endif -%}
          {%- if hours > 0 -%}
            {%- if hours == 1 -%}
              1 hour
            {%- else -%}
              {{ hours }} hours
            {%- endif -%}
          {%- endif -%}
  - platform: plex
  
# Polling das cameras para notificar sobre movimento
binary_sensor:
  - platform: template
    sensors:
      tv_sala:
        value_template: "{{ is_state('device_tracker.tv_sala', 'home') }}"
        friendly_name: TV Sala
      chromecast:
        value_template: "{{ is_state('device_tracker.chromecast', 'home') }}"
        friendly_name: Chromecast
      ps3:
        value_template: "{{ is_state('device_tracker.ps3', 'home') }}"
        friendly_name: PS3
      impressora:
        value_template: "{{ is_state('device_tracker.impressora', 'home') }}"
        friendly_name: Impressora
      camera_gabi:
        value_template: "{{ is_state('device_tracker.camera_gabi', 'home') }}"
        friendly_name: Câmera Gabi
      camera_garagem:
        value_template: "{{ is_state('device_tracker.camera_garagem', 'home') }}"
        friendly_name: Câmera Garagem
      camera_lavanderia:
        value_template: "{{ is_state('device_tracker.camera_lavanderia', 'home') }}"
        friendly_name: Câmera Lavanderia
      asus_pc:
        value_template: "{{ is_state('device_tracker.asus_pc', 'home') }}"
        friendly_name: Asus PC
      tablet_idea:
        value_template: "{{ is_state('device_tracker.tablet_idea', 'home') }}"
        friendly_name: Tablet Idea
    
  - platform: command_line
    name: Movimento Garagem
    friendly_name: Movimento
    command: !secret cam01_movimento 
    payload_on: 1
    payload_off: 0
    device_class: motion
    scan_interval: 15
  - platform: command_line
    name: Movimento Quarto Gabi
    friendly_name: Movimento
    command: !secret cam02_movimento 
    payload_on: 1
    payload_off: 0
    device_class: motion
    scan_interval: 15
  - platform: command_line
    name: Movimento Lavanderia
    friendly_name: Movimento
    command: !secret cam03_movimento 
    payload_on: 1
    payload_off: 0
    device_class: motion
    scan_interval: 60

# Camera da garagem
camera:
  - platform: mjpeg
    mjpeg_url: !secret cam01_video
    still_image_url: !secret cam01_photo
    username: admin
    password: !secret password01
    name: Garagem
  - platform: mjpeg
    mjpeg_url: !secret cam02_video
    still_image_url: !secret cam02_photo
    username: admin
    password: !secret password01
    name: Quarto Gabi
# Camera nao permite autenticação como as demais
  - platform: mjpeg
    mjpeg_url: !secret cam03_video 
    name: Lavanderia

# Rastreamento de dispositivos (e pessoas)
#Lembre-se de sudo setcap cap_net_raw,cap_net_admin,cap_net_bind_service+eip /usr/bin/nmap
device_tracker:
  - platform: nmap_tracker
    hosts: 192.168.0.1/24
    scan_options: "--privileged -sN --host-timeout 5s  "
    interval_seconds: 30
    consider_home: 600
#    home_interval: 5
    exclude:
      - 192.168.0.11
  - platform: gpslogger

# VLC = player do OPi
media_player:
  - platform: vlc
    name: Orange Pi

# Mosquitto broker
#mqtt:
#  broker: localhost

# LIRC
lirc:

# Para gerar TTS, que podem ser enviados pra um media_player
tts:
  - platform: google
    language: 'pt-br'

# Interruptores para acioanr o portao da garagem
# deligar deteccao de movimento das cameras
switch:
  platform: command_line
  switches:
    portao_garagem:
      command_on: !secret cam01_out_on 
      command_off: !secret cam01_out_off 
      friendly_name: Portao Garagem
    tomada_quarto_gabi:
      command_on: !secret cam02_out_on 
      command_off: !secret cam02_out_off 
      friendly_name: Tomada Quarto Gabi 
    deteccao_movimento_garagem:
      command_on: !secret cam01_motion_detect_on
      command_off: !secret cam01_motion_detect_off
      command_state: !secret cam01_motion_detect_state
      value_template: '{{ value == "1" }}'
      friendly_name: Sensor de movimento
    deteccao_movimento_quarto_gabi:
      command_on: !secret cam02_motion_detect_on 
      command_off: !secret cam02_motion_detect_off 
      command_state: !secret cam02_motion_detect_state
      value_template: '{{ value == "1" }}'
      friendly_name: Sensor de movimento
#    deteccao_movimento_lavanderia:
#      command_on: !secret cam03_motion_detect_on 
#      command_off: !secret cam03_motion_detect_off 
#     command_state: !secret cam03_motion_detect_state
#      value_template: '{{ value == "1" }}'
#      friendly_name: Sensor de movimento
shell_command:
  cam01_salva_snapshot_cmd: '/home/pi/.homeassistant/shell_command/cam01_salva_snapshot.sh' 
  cam02_salva_snapshot_cmd: '/home/pi/.homeassistant/shell_command/cam02_salva_snapshot.sh' 
  cam03_salva_snapshot_cmd: '/home/pi/.homeassistant/shell_command/cam03_salva_snapshot.sh' 
  cam01_salva_video_cmd: '/home/pi/.homeassistant/shell_command/cam01_salva_video.sh' 
  cam02_salva_video_cmd: '/home/pi/.homeassistant/shell_command/cam02_salva_video.sh' 
  cam03_salva_video_cmd: '/home/pi/.homeassistant/shell_command/cam03_salva_video.sh' 
# Seletor das radios
# Necessário associar cada rádio no script
# Necessário listar cada radio no Dialogflow
input_select:
  radio_station:
    name: 'Estação:'
    options:
      - Desligado
      - Coca-Cola FM
      - Villa Mix
      - CDL FM
      - 98 FM
      - Jovem Pan
      - Itatiaia
      - Jovem Pan Pagode
      - Classic FM
      - Calm Radio - Sleep
      - Bossa Jazz Brasil
      - Alvorada
      - Kiss FM
      - 89 A Radio Rock
    initial: Desligado
  chromecast_radio:
    name: 'Alto-falante:'
    options:
      - OrangePi
      - Chromecast
    initial: OrangePi
    icon: mdi:speaker-wireless
input_number: 
  volume_radio:
    name: Volume
    icon: mdi:volume-high
    initial: 0.5
    min: 0
    max: 1
    step: 0.05
    

#IFTTT
ifttt:
  key: !secret ifttt_key

# Comandos de voz do Api.ai e Actions on Google
dialogflow:

#Notificações no celular ou computador (android / chrome apenas)
notify:
  - name: Chrome_Notifier
    platform: html5
    gcm_api_key: !secret gcm_api_key 
    gcm_sender_id: !secret gcm_sender_id

intent_script: !include intent_script.yaml
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
